# Spring profiles  
spring:         
    # DATASOURCE  
    datasource:
             druid:
                 driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
                 url: jdbc:sqlserver://10.2.21.199;instanceName=sqlserver2008;DatabaseName=kmhhos
                 username: sa  
                 password: sa123$
                 initial-size: 5 
                 max-active: 20
                 min-idle: 2 
                 max-wait: 60000
                 validation-query: SELECT 1
                 test-on-borrow : false
                 test-on-return : false
                 test-while-idle : true
                 time-between-eviction-runs-millis : 60000
                 min-evictable-idle-time-millis : 25200000
                 filters : mergeStat,wall
                 stat-view-servlet:
                              login-username : admin
                              login-password : Kmjky+2017
# spring redis  
    redis: 
        # Redis服务器地址  
        host: 10.2.21.199  
        # Redis服务器连接端口  
        port: 6379  
        # Redis服务器连接密码（默认为空）  
        password:
        pool:  
           # 连接池最大连接数（使用负值表示没有限制）  
           max-active: 50  
           # 连接池中的最大空闲连接  
           min-idle: 10  
           # 连接池最大阻塞等待时间（使用负值表示没有限制）  
           max-wait: -1  
           # 连接池中的最小空闲连接  
           max-idle: 50  
        # 连接超时时间（毫秒）  
        timeout: 2000
# system config
system:
     authCodeTimeout: 120
     tokenTimeout: 1800 
     uploadUrl: http://10.2.21.199:6060/zsyy_resource
     is-test: false 
     version: 2014-06-30 
     rest-server: api.ucpaas.com 
     http-ssl-ip: 0 
     http-ssl-port: 0     
     is-authCode: false